name: eachreach_front
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  google_sign_in: ^6.2.1
  http: ^1.2.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

http: ^0.13.4
lutter_secure_storage: ^5.0.2
google_sign_in: ^5.0.7
intl: ^0.17.0
provider: ^6.0.1

